const Physics = [

{q:"Powerhouse of cell?", a:"Mitochondria", o:["Nucleus","Mitochondria","Ribosome","Cortex"]},
{q:"Control center of cell?", a:"Nucleus", o:["Vacuole","Nucleus","Chloroplast","Cell wall"]},
{q:"Site of protein synthesis?", a:"Ribosome", o:["Golgi body","Ribosome","Lysosome","Nucleus"]},
{q:"Green pigment in plants?", a:"Chlorophyll", o:["Hemoglobin","Chlorophyll","Melanin","Carotene"]},
{q:"Basic unit of life?", a:"Cell", o:["Tissue","Organ","Cell","Atom"]},
{q:"Largest organ in human body?", a:"Skin", o:["Heart","Skin","Liver","Brain"]},
{q:"Universal donor blood group?", a:"O negative", o:["A positive","B positive","O negative","AB positive"]},
{q:"Universal recipient blood group?", a:"AB positive", o:["O negative","A negative","AB positive","B negative"]},
{q:"Process by which plants make food?", a:"Photosynthesis", o:["Respiration","Photosynthesis","Digestion","Transpiration"]},
{q:"Gas released during photosynthesis?", a:"Oxygen", o:["Carbon dioxide","Nitrogen","Oxygen","Hydrogen"]},

{q:"Instrument used to see microorganisms?", a:"Microscope", o:["Telescope","Microscope","Barometer","Periscope"]},
{q:"Functional unit of kidney?", a:"Nephron", o:["Neuron","Nephron","Alveolus","Atrium"]},
{q:"Red pigment in blood?", a:"Hemoglobin", o:["Melanin","Chlorophyll","Hemoglobin","Insulin"]},
{q:"Organ that pumps blood?", a:"Heart", o:["Liver","Heart","Kidney","Lungs"]},
{q:"Largest part of the brain?", a:"Cerebrum", o:["Medulla","Cerebellum","Cerebrum","Pons"]},
{q:"Site of gas exchange in lungs?", a:"Alveoli", o:["Bronchi","Alveoli","Trachea","Larynx"]},
{q:"Father of Evolution?", a:"Charles Darwin", o:["Isaac Newton","Albert Einstein","Charles Darwin","Louis Pasteur"]},
{q:"Father of Genetics?", a:"Gregor Mendel", o:["Watson","Charles Darwin","Gregor Mendel","Crick"]},
{q:"DNA full meaning?", a:"Deoxyribonucleic acid", o:["Ribonucleic acid","Deoxyribonucleic acid","Amino acid","Nucleic protein"]},
{q:"RNA full meaning?", a:"Ribonucleic acid", o:["Deoxyribonucleic acid","Ribonucleic acid","Nitric acid","Amino acid"]},

{q:"Number of chromosomes in humans?", a:"46", o:["23","44","46","48"]},
{q:"Cell division in body cells?", a:"Mitosis", o:["Meiosis","Fusion","Mitosis","Budding"]},
{q:"Cell division in sex cells?", a:"Meiosis", o:["Mitosis","Binary fission","Meiosis","Fragmentation"]},
{q:"Movement of water through semi-permeable membrane?", a:"Osmosis", o:["Diffusion","Respiration","Osmosis","Filtration"]},
{q:"Loss of water vapor from leaves?", a:"Transpiration", o:["Respiration","Photosynthesis","Transpiration","Diffusion"]},
{q:"Organ that detoxifies harmful substances?", a:"Liver", o:["Kidney","Heart","Liver","Pancreas"]},
{q:"Part of plant that absorbs water?", a:"Root", o:["Stem","Leaf","Root","Flower"]},
{q:"Male reproductive cell?", a:"Sperm", o:["Ovum","Sperm","Embryo","Zygote"]},
{q:"Female reproductive cell?", a:"Ovum", o:["Sperm","Zygote","Foetus","Ovum"]},
{q:"Breathing out is called?", a:"Exhalation", o:["Inhalation","Exhalation","Respiration","Ventilation"]},

{q:"Breathing in is called?", a:"Inhalation", o:["Exhalation","Inhalation","Circulation","Diffusion"]},
{q:"Rigid outer layer of plant cell?", a:"Cell wall", o:["Cell membrane","Cell wall","Cytoplasm","Nucleus"]},
{q:"Jelly-like substance in cell?", a:"Cytoplasm", o:["Nucleus","Cytoplasm","Mitochondria","Golgi body"]},
{q:"Sense organ for hearing?", a:"Ear", o:["Eye","Ear","Nose","Skin"]},
{q:"Sense organ for sight?", a:"Eye", o:["Ear","Nose","Eye","Tongue"]},
{q:"Human gestation period?", a:"9 months", o:["7 months","8 months","9 months","10 months"]},
{q:"Organ that produces insulin?", a:"Pancreas", o:["Liver","Pancreas","Kidney","Heart"]},
{q:"Plant tissue transporting water?", a:"Xylem", o:["Phloem","Xylem","Cortex","Cambium"]},
{q:"Plant tissue transporting food?", a:"Phloem", o:["Xylem","Cortex","Phloem","Pith"]},
{q:"Energy currency of the cell?", a:"ATP", o:["DNA","ATP","RNA","ADP"]},

{q:"Organ responsible for breathing?", a:"Lungs", o:["Heart","Liver","Lungs","Kidney"]},
{q:"Bone that protects the brain?", a:"Skull", o:["Rib","Femur","Skull","Pelvis"]},
{q:"Smallest bone in human body?", a:"Stapes", o:["Femur","Stapes","Tibia","Humerus"]},
{q:"Blood vessels carrying blood away from heart?", a:"Arteries", o:["Veins","Capillaries","Arteries","Nerves"]},
{q:"Blood vessels carrying blood to heart?", a:"Veins", o:["Arteries","Capillaries","Veins","Bronchi"]},
{q:"Main organ of circulatory system?", a:"Heart", o:["Liver","Lungs","Heart","Kidney"]},
{q:"Organ of balance in ear?", a:"Semicircular canal", o:["Cochlea","Semicircular canal","Eardrum","Pinna"]},
{q:"Part of eye controlling light entry?", a:"Iris", o:["Retina","Iris","Cornea","Lens"]},
{q:"Organ that filters blood?", a:"Kidney", o:["Liver","Kidney","Pancreas","Heart"]},
{q:"Breakdown of food in cells?", a:"Respiration", o:["Photosynthesis","Digestion","Respiration","Excretion"]},
{q:"Process of removal of waste from body?", a:"Excretion", o:["Respiration","Excretion","Digestion","Circulation"]},
{q:"Organ responsible for excretion in humans?", a:"Kidney", o:["Liver","Kidney","Lungs","Skin"]},
{q:"Chemical process of breaking down food?", a:"Digestion", o:["Respiration","Digestion","Absorption","Assimilation"]},
{q:"Tiny air sacs in lungs?", a:"Alveoli", o:["Bronchi","Trachea","Alveoli","Larynx"]},
{q:"Part of plant where photosynthesis mainly occurs?", a:"Leaf", o:["Root","Stem","Leaf","Flower"]},
{q:"Opening on leaf surface?", a:"Stomata", o:["Lenticel","Stomata","Cuticle","Node"]},
{q:"Fluid part of blood?", a:"Plasma", o:["Platelets","Plasma","WBC","RBC"]},
{q:"Cells that fight infection?", a:"White blood cells", o:["Red blood cells","Platelets","White blood cells","Plasma"]},
{q:"Cells responsible for clotting?", a:"Platelets", o:["RBC","WBC","Platelets","Plasma"]},
{q:"Blood cells carrying oxygen?", a:"Red blood cells", o:["White blood cells","Platelets","Red blood cells","Plasma"]},
{q:"Longest bone in human body?", a:"Femur", o:["Tibia","Humerus","Femur","Radius"]},
{q:"Joint that allows movement in all directions?", a:"Ball and socket joint", o:["Hinge joint","Pivot joint","Ball and socket joint","Fixed joint"]},
{q:"Organ that controls body coordination?", a:"Cerebellum", o:["Cerebrum","Cerebellum","Medulla","Pons"]},
{q:"Part of brain controlling involuntary actions?", a:"Medulla", o:["Cerebrum","Medulla","Cerebellum","Hypothalamus"]},
{q:"Hormone controlling blood sugar?", a:"Insulin", o:["Adrenaline","Insulin","Thyroxine","Estrogen"]},
{q:"Gland producing thyroxine?", a:"Thyroid gland", o:["Pituitary gland","Adrenal gland","Thyroid gland","Pancreas"]},
{q:"Largest gland in human body?", a:"Liver", o:["Pancreas","Liver","Thyroid","Salivary gland"]},
{q:"Organ that stores bile?", a:"Gall bladder", o:["Liver","Pancreas","Gall bladder","Kidney"]},
{q:"Process of taking in food by organisms?", a:"Ingestion", o:["Egestion","Ingestion","Digestion","Absorption"]},
{q:"Removal of undigested food?", a:"Egestion", o:["Excretion","Digestion","Egestion","Respiration"]},

{q:"Type of reproduction involving one parent?", a:"Asexual reproduction", o:["Sexual reproduction","Asexual reproduction","Fertilization","Pollination"]},
{q:"Fusion of male and female gametes?", a:"Fertilization", o:["Pollination","Fertilization","Budding","Fragmentation"]},
{q:"Transfer of pollen to stigma?", a:"Pollination", o:["Fertilization","Pollination","Germination","Transpiration"]},
{q:"Growth of seed into plant?", a:"Germination", o:["Pollination","Fertilization","Germination","Budding"]},
{q:"Organ for smell?", a:"Nose", o:["Eye","Ear","Nose","Tongue"]},
{q:"Organ for taste?", a:"Tongue", o:["Nose","Skin","Tongue","Eye"]},
{q:"Hard covering of seed?", a:"Seed coat", o:["Cotyledon","Seed coat","Embryo","Endosperm"]},
{q:"Food stored in seed leaves?", a:"Cotyledon", o:["Embryo","Endosperm","Cotyledon","Seed coat"]},
{q:"Stage before adult in frog?", a:"Tadpole", o:["Larva","Tadpole","Pupa","Nymph"]},
{q:"Change from larva to adult?", a:"Metamorphosis", o:["Mutation","Metamorphosis","Fertilization","Adaptation"]},

{q:"Organism that makes its own food?", a:"Autotroph", o:["Heterotroph","Autotroph","Parasite","Saprophyte"]},
{q:"Organism that depends on others for food?", a:"Heterotroph", o:["Autotroph","Producer","Heterotroph","Herbivore"]},
{q:"Animals that eat plants only?", a:"Herbivores", o:["Carnivores","Omnivores","Herbivores","Parasites"]},
{q:"Animals that eat flesh?", a:"Carnivores", o:["Herbivores","Carnivores","Omnivores","Producers"]},
{q:"Animals that eat both plants and animals?", a:"Omnivores", o:["Carnivores","Herbivores","Omnivores","Parasites"]},
{q:"Relationship where one benefits and other harmed?", a:"Parasitism", o:["Mutualism","Commensalism","Parasitism","Symbiosis"]},
{q:"Relationship where both benefit?", a:"Mutualism", o:["Parasitism","Mutualism","Competition","Predation"]},
{q:"Study of living organisms?", a:"Biology", o:["Chemistry","Physics","Biology","Geography"]},
{q:"Branch of biology dealing with plants?", a:"Botany", o:["Zoology","Ecology","Botany","Genetics"]},
{q:"Branch of biology dealing with animals?", a:"Zoology", o:["Botany","Genetics","Zoology","Anatomy"]},

{q:"Study of heredity?", a:"Genetics", o:["Ecology","Genetics","Botany","Zoology"]},
{q:"Study of environment and organisms?", a:"Ecology", o:["Ecology","Genetics","Anatomy","Physiology"]},
{q:"Study of body structure?", a:"Anatomy", o:["Physiology","Anatomy","Ecology","Genetics"]},
{q:"Study of body functions?", a:"Physiology", o:["Anatomy","Physiology","Botany","Zoology"]},
{q:"Organ that produces sperm?", a:"Testis", o:["Ovary","Testis","Uterus","Penis"]},
{q:"Organ that produces ova?", a:"Ovary", o:["Testis","Ovary","Uterus","Vagina"]},
{q:"Temporary structure formed after fertilization?", a:"Zygote", o:["Embryo","Foetus","Zygote","Gamete"]},
{q:"Organ that houses fetus?", a:"Uterus", o:["Ovary","Uterus","Vagina","Testis"]},
{q:"Outer protective covering of body?", a:"Skin", o:["Hair","Skin","Nail","Muscle"]},
{q:"System responsible for body movement?", a:"Muscular system", o:["Nervous system","Digestive system","Muscular system","Respiratory system"]},
{q:"System that controls body activities?", a:"Nervous system", o:["Digestive system","Nervous system","Respiratory system","Circulatory system"]},
{q:"System responsible for transporting nutrients and oxygen?", a:"Circulatory system", o:["Respiratory system","Circulatory system","Digestive system","Excretory system"]},
{q:"System responsible for breathing?", a:"Respiratory system", o:["Digestive system","Respiratory system","Nervous system","Muscular system"]},
{q:"System responsible for breaking down food?", a:"Digestive system", o:["Respiratory system","Digestive system","Circulatory system","Skeletal system"]},
{q:"System that removes liquid waste?", a:"Excretory system", o:["Digestive system","Excretory system","Respiratory system","Nervous system"]},
{q:"Framework of bones in body?", a:"Skeleton", o:["Muscle","Skeleton","Cartilage","Ligament"]},
{q:"Tissue connecting bone to bone?", a:"Ligament", o:["Tendon","Cartilage","Ligament","Muscle"]},
{q:"Tissue connecting muscle to bone?", a:"Tendon", o:["Ligament","Tendon","Cartilage","Nerve"]},
{q:"Flexible tissue at joints?", a:"Cartilage", o:["Bone","Ligament","Cartilage","Muscle"]},
{q:"Main gas used in respiration?", a:"Oxygen", o:["Carbon dioxide","Nitrogen","Oxygen","Hydrogen"]},

{q:"Waste gas from respiration?", a:"Carbon dioxide", o:["Oxygen","Carbon dioxide","Nitrogen","Helium"]},
{q:"Organ that produces bile?", a:"Liver", o:["Gall bladder","Liver","Pancreas","Kidney"]},
{q:"Chemical that speeds up reactions in body?", a:"Enzyme", o:["Hormone","Enzyme","Vitamin","Mineral"]},
{q:"Deficiency of vitamin C causes?", a:"Scurvy", o:["Rickets","Scurvy","Kwashiorkor","Anemia"]},
{q:"Deficiency of vitamin D causes?", a:"Rickets", o:["Scurvy","Anemia","Rickets","Goitre"]},
{q:"Iron deficiency causes?", a:"Anemia", o:["Rickets","Scurvy","Anemia","Goitre"]},
{q:"Protein deficiency in children?", a:"Kwashiorkor", o:["Marasmus","Kwashiorkor","Scurvy","Rickets"]},
{q:"Balanced diet contains?", a:"All nutrients", o:["Proteins only","Carbohydrates only","All nutrients","Fats only"]},
{q:"Organism that decomposes dead matter?", a:"Decomposer", o:["Producer","Consumer","Decomposer","Herbivore"]},
{q:"Green plants are called?", a:"Producers", o:["Consumers","Decomposers","Producers","Parasites"]},

{q:"First trophic level in food chain?", a:"Producer", o:["Producer","Consumer","Decomposer","Carnivore"]},
{q:"Energy source for Earth?", a:"Sun", o:["Moon","Stars","Sun","Wind"]},
{q:"Layer of atmosphere protecting from UV?", a:"Ozone layer", o:["Troposphere","Stratosphere","Ozone layer","Mesosphere"]},
{q:"Process plants lose water droplets?", a:"Guttation", o:["Transpiration","Guttation","Respiration","Diffusion"]},
{q:"Type of roots in maize?", a:"Fibrous root", o:["Tap root","Fibrous root","Adventitious root","Prop root"]},
{q:"Type of roots in beans?", a:"Tap root", o:["Fibrous root","Tap root","Adventitious root","Aerial root"]},
{q:"Opening in human skin for sweat?", a:"Sweat pore", o:["Hair follicle","Sweat pore","Sebaceous gland","Nerve ending"]},
{q:"Hormone responsible for male traits?", a:"Testosterone", o:["Estrogen","Progesterone","Testosterone","Insulin"]},
{q:"Hormone responsible for female traits?", a:"Estrogen", o:["Testosterone","Estrogen","Adrenaline","Thyroxine"]},
{q:"Organ that controls hormones?", a:"Pituitary gland", o:["Thyroid gland","Adrenal gland","Pituitary gland","Pancreas"]},

{q:"Rapid increase in population?", a:"Population explosion", o:["Immigration","Population explosion","Emigration","Migration"]},
{q:"Movement of organisms into area?", a:"Immigration", o:["Emigration","Immigration","Migration","Adaptation"]},
{q:"Movement out of area?", a:"Emigration", o:["Immigration","Emigration","Mutation","Adaptation"]},
{q:"Permanent change in genetic material?", a:"Mutation", o:["Adaptation","Mutation","Evolution","Variation"]},
{q:"Differences among individuals?", a:"Variation", o:["Mutation","Variation","Heredity","Evolution"]},
{q:"Passing traits from parents to offspring?", a:"Heredity", o:["Variation","Heredity","Mutation","Adaptation"]},
{q:"Gradual change in organisms over time?", a:"Evolution", o:["Mutation","Evolution","Adaptation","Variation"]},
{q:"Ability to survive in environment?", a:"Adaptation", o:["Evolution","Adaptation","Mutation","Competition"]},
{q:"Competition occurs when organisms?", a:"Fight for resources", o:["Cooperate","Fight for resources","Reproduce","Hibernate"]},
{q:"Group of similar organisms that interbreed?", a:"Species", o:["Genus","Family","Species","Order"]},

{q:"Scientific naming uses how many names?", a:"Two", o:["One","Two","Three","Four"]},
{q:"Scientific name of human?", a:"Homo sapiens", o:["Homo erectus","Homo sapiens","Pan troglodytes","Australopithecus"]},
{q:"Largest ecosystem?", a:"Biosphere", o:["Biome","Habitat","Biosphere","Community"]},
{q:"Place where organism lives?", a:"Habitat", o:["Niche","Habitat","Biome","Ecosystem"]},
{q:"Role of organism in ecosystem?", a:"Niche", o:["Habitat","Biome","Niche","Community"]},
{q:"Group of organisms of same species?", a:"Population", o:["Community","Population","Ecosystem","Biome"]},
{q:"Different populations living together?", a:"Community", o:["Population","Community","Biome","Species"]},
{q:"Living and non-living components together?", a:"Ecosystem", o:["Habitat","Ecosystem","Biome","Biosphere"]},
{q:"Large regional ecosystem?", a:"Biome", o:["Habitat","Biome","Community","Species"]},
{q:"Process of water cycle returning water to Earth?", a:"Precipitation", o:["Evaporation","Condensation","Precipitation","Transpiration"]}
];
export default Physics;
